services:
  postgres:
    image: postgres:alpine
    container_name: nerimity_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nerimity-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: nerimity_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - nerimity-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: nerimity_api
    restart: always
    command: sh -c "npx prisma migrate deploy && node dist/index.mjs --api"
    ports:
      - "${API_PORT}:8080"
    environment:
      - DEV_MODE=${DEV_MODE}
      - APP_NAME=${APP_NAME}
      - CLIENT_URL=${CLIENT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - API_PORT=8080
      - WS_PORT=8081
      # Secrets
      - JWT_SECRET=${JWT_SECRET}
      - JWT_CONNECTIONS_SECRET=${JWT_CONNECTIONS_SECRET}
      - JWT_WEBHOOK_SECRET=${JWT_WEBHOOK_SECRET}
      - NERIMITY_CDN_SECRET=${NERIMITY_CDN_SECRET}
      - EXTERNAL_EMBED_SECRET=${EXTERNAL_EMBED_SECRET}
      - CONNECTIONS_SECRET=${CONNECTIONS_SECRET}
      # Mailer
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      # Other
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - TENOR_API_KEY=${TENOR_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nerimity-network

  ws:
    build: .
    container_name: nerimity_ws
    restart: always
    command: node dist/index.mjs --ws
    ports:
      - "${WS_PORT}:8081"
    environment:
      - DEV_MODE=${DEV_MODE}
      - APP_NAME=${APP_NAME}
      - CLIENT_URL=${CLIENT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - API_PORT=8080
      - WS_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nerimity-network

networks:
  nerimity-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
